const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {URL}=require('url');const E=require('./game-engine');
const PORT=Number(process.env.PORT||3000),HOST='0.0.0.0',PUBLIC=path.join(__dirname,'public'),rooms=new Map(),MAX_PLAYERS=14,MIN_PLAYERS=4;
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};
function cleanName(v){const s=String(v||'').replace(/\s+/g,' ').trim().slice(0,14);if(!s)throw Error('닉네임을 입력해 주세요.');return s}
function cleanMessage(v){const s=String(v||'').replace(/\s+/g,' ').trim().slice(0,120);if(!s)throw Error('메시지를 입력해 주세요.');return s}
function cleanCode(v){return String(v||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,6)}
function newCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let z=0;z<999;z++){let s='';for(let i=0;i<5;i++)s+=chars[Math.floor(Math.random()*chars.length)];if(!rooms.has(s))return s}throw Error('방 코드를 만들지 못했습니다.')}
function getRoom(v){const r=rooms.get(cleanCode(v));if(!r)throw Error('방을 찾을 수 없습니다.');return r}
function auth(p){const r=getRoom(p.roomCode),u=r.players.find(x=>x.id===p.playerId&&x.token===p.reconnectToken);if(!u)throw Error('재접속 정보가 올바르지 않습니다.');return{r,u}}
function session(r,u){return{roomCode:r.code,playerId:u.id,reconnectToken:u.token}}
function roleName(i,n){if(i===0)return'대 달무티';if(i===1)return'소 달무티';if(i===n-2)return'소 농노';if(i===n-1)return'대 농노';return'상인'}
function normalizeGameRoles(g){g.players.sort((a,b)=>a.roleIndex-b.roleIndex);g.players.forEach((p,i)=>{p.roleIndex=i;p.seat=i;p.role=roleName(i,g.players.length)})}
function isActivePlayer(r,id){return !!r.game?.players.some(p=>p.id===id)}
function publicGame(r,viewer){const g=r.game;if(!g)return null;return{status:g.status,handNumber:g.handNumber,phase:g.phase,currentPlayerId:g.currentPlayerId,pile:g.pile?{...g.pile,playerName:g.players.find(p=>p.id===g.pile.playerId)?.name||''}:null,passers:g.passers,finishOrder:g.finishOrder,winnerId:g.winnerId,logs:g.logs.slice(-50),viewerWaiting:!g.players.some(p=>p.id===viewer),tax:g.phase==='revolution'?{eligibleForViewer:g.tax.eligible.includes(viewer),declined:g.tax.declined.includes(viewer)}:g.phase==='tax'?{stage:g.tax.stage,pending:g.currentPlayerId===viewer?g.tax.pending:null}:null,players:g.players.map(p=>({id:p.id,name:p.name,role:p.role,roleIndex:p.roleIndex,connected:p.connected,handCount:p.hand.length,finished:p.finished,finishPlace:p.finishPlace,hand:p.id===viewer?p.hand.map(c=>({id:c.id,rank:c.rank})):null}))}}
function state(r,v){return{room:{code:r.code,maxPlayers:MAX_PLAYERS,hostId:r.hostId,players:r.players.map(p=>({id:p.id,name:p.name,connected:p.connected,waiting:!!r.game&&!isActivePlayer(r,p.id)})),started:!!r.game,chat:r.chat.slice(-60)},viewerId:v,game:publicGame(r,v)}}
function sse(res,event,data){try{res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);return true}catch{return false}}
function emit(r){if(r.game)for(const gp of r.game.players){const lp=r.players.find(x=>x.id===gp.id);gp.connected=!!lp?.connected}for(const p of r.players)if(p.stream&&!sse(p.stream,'state',state(r,p.id))){p.stream=null;p.connected=false}}
function transferHost(r){if(!r.players.find(p=>p.id===r.hostId))r.hostId=r.players[0]?.id||null}
function addWaitingPlayersForNextHand(r){const g=r.game;const newcomers=r.players.filter(p=>!g.players.some(x=>x.id===p.id));if(!newcomers.length)return[];for(const u of newcomers){g.players.push({id:u.id,name:u.name,connected:u.connected,seat:g.players.length,roleIndex:g.players.length,role:'대 농노',hand:[],finished:false,finishPlace:null})}normalizeGameRoles(g);return newcomers}
function removeRoomPlayer(r,target){if(target.stream){sse(target.stream,'kicked',{message:'방장에 의해 강퇴되었습니다.'});target.stream.end();target.stream=null}r.players=r.players.filter(x=>x.id!==target.id);transferHost(r)}
function restartAfterActiveKick(r,targetName,targetId){const g=r.game;g.players=g.players.filter(p=>p.id!==targetId);g.finishOrder=g.finishOrder.filter(id=>id!==targetId);g.passers=g.passers.filter(id=>id!==targetId);normalizeGameRoles(g);const newcomers=addWaitingPlayersForNextHand(r);if(g.players.length<MIN_PLAYERS){r.game=null;return{restarted:false,newcomers}}E.restartHand(g);g.logs.push(`${targetName}님을 제외하고 새 판을 시작했습니다.`);if(newcomers.length)g.logs.push(`${newcomers.map(x=>x.name).join(', ')}님이 대농노 쪽 계급으로 합류했습니다.`);return{restarted:true,newcomers}}
const A={
'create-room':p=>{const u={id:crypto.randomUUID(),token:crypto.randomUUID(),name:cleanName(p.name),connected:true,stream:null};const r={code:newCode(),hostId:u.id,players:[u],game:null,chat:[]};rooms.set(r.code,r);return{session:session(r,u),state:state(r,u.id)}},
'join-room':p=>{const r=getRoom(p.roomCode),name=cleanName(p.name);const existing=r.players.find(x=>x.name.toLowerCase()===name.toLowerCase());if(existing){if(existing.connected)throw Error('같은 닉네임이 이미 접속 중입니다.');existing.token=crypto.randomUUID();existing.connected=true;emit(r);return{session:session(r,existing),state:state(r,existing.id)}}if(r.players.length>=MAX_PLAYERS)throw Error('방이 가득 찼습니다. 최대 14명입니다.');const u={id:crypto.randomUUID(),token:crypto.randomUUID(),name,connected:true,stream:null};r.players.push(u);if(r.game)r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:`${name}님이 입장했습니다. 다음 판부터 대농노로 합류합니다.`,at:Date.now()});emit(r);return{session:session(r,u),state:state(r,u.id)}},
'reconnect-session':p=>{const {r,u}=auth(p);u.connected=true;emit(r);return{session:session(r,u),state:state(r,u.id)}},
'leave-room':p=>{const {r,u}=auth(p);if(u.stream){u.stream.end();u.stream=null}if(r.game&&isActivePlayer(r,u.id)){u.connected=false}else{r.players=r.players.filter(x=>x.id!==u.id);transferHost(r);if(!r.players.length)rooms.delete(r.code)}emit(r);return{}},
'kick-player':p=>{const {r,u}=auth(p);if(u.id!==r.hostId)throw Error('방장만 강퇴할 수 있습니다.');const target=r.players.find(x=>x.id===p.targetPlayerId);if(!target)throw Error('대상을 찾을 수 없습니다.');if(target.id===u.id)throw Error('자기 자신은 강퇴할 수 없습니다.');const active=isActivePlayer(r,target.id),name=target.name;removeRoomPlayer(r,target);let restarted=false;if(active&&r.game){const result=restartAfterActiveKick(r,name,target.id);restarted=result.restarted}r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:active?(restarted?`${name}님을 제외하고 새 판을 시작했습니다.`:`${name}님이 강퇴되었습니다. 인원이 4명 미만이라 로비로 돌아갑니다.`):`${name}님이 방장에 의해 강퇴되었습니다.`,at:Date.now()});emit(r);return{}},
'start-game':p=>{const {r,u}=auth(p);if(u.id!==r.hostId)throw Error('방장만 시작할 수 있습니다.');if(r.players.length<MIN_PLAYERS)throw Error('최소 4명이 필요합니다.');if(r.players.length>MAX_PLAYERS)throw Error('최대 14명까지 가능합니다.');r.game=E.createGame(r.players.map(x=>({id:x.id,name:x.name,connected:true})));emit(r);return{}},
'declare-revolution':p=>{const {r,u}=auth(p);E.declareRevolution(r.game,u.id,!!p.greater);emit(r);return{}},
'decline-revolution':p=>{const {r,u}=auth(p);E.declineRevolution(r.game,u.id);emit(r);return{}},
'tax-return':p=>{const {r,u}=auth(p);E.taxReturn(r.game,u.id,p.cardIds);emit(r);return{}},
'play-cards':p=>{const {r,u}=auth(p);E.playCards(r.game,u.id,p.cardIds);emit(r);return{}},
'pass':p=>{const {r,u}=auth(p);E.pass(r.game,u.id);emit(r);return{}},
'next-hand':p=>{const {r,u}=auth(p);const g=r.game;if(g.phase!=='results')throw Error('현재 판이 끝나지 않았습니다.');const gd=g.players.find(x=>x.roleIndex===0);if(u.id!==gd.id)throw Error('새 대 달무티만 다음 판을 시작할 수 있습니다.');const newcomers=addWaitingPlayersForNextHand(r);if(newcomers.length)g.logs.push(`${newcomers.map(x=>x.name).join(', ')}님이 새 대농노 계급으로 합류합니다.`);E.nextHand(g,u.id);emit(r);return{}},
'send-chat':p=>{const {r,u}=auth(p);r.chat.push({id:crypto.randomUUID(),playerId:u.id,name:u.name,text:cleanMessage(p.message),at:Date.now()});if(r.chat.length>80)r.chat.splice(0,r.chat.length-80);emit(r);return{}}
};
function json(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(b)});res.end(b)}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on('error',no)})}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='POST'&&u.pathname==='/api/action'){const p=await body(req),fn=A[p.type];if(!fn)throw Error('알 수 없는 요청입니다.');return json(res,200,{ok:true,...fn(p)})}if(req.method==='GET'&&u.pathname==='/api/events'){const p=Object.fromEntries(u.searchParams),{r,u:pl}=auth(p);if(pl.stream)pl.stream.end();pl.connected=true;res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});pl.stream=res;sse(res,'state',state(r,pl.id));req.on('close',()=>{if(pl.stream===res){pl.stream=null;pl.connected=false;emit(r)}});return}let f=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));f=path.normalize(f).replace(/^(\.\.[/\\])+/, '');const full=path.join(PUBLIC,f);if(!full.startsWith(PUBLIC)||!fs.existsSync(full)||fs.statSync(full).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[path.extname(full)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(full).pipe(res)}catch(e){json(res,400,{ok:false,error:e.message||'오류가 발생했습니다.'})}});
function ips(){const a=[];for(const xs of Object.values(os.networkInterfaces()))for(const x of xs||[])if(x.family==='IPv4'&&!x.internal)a.push(x.address);return a}
server.listen(PORT,HOST,()=>{console.log('\nGreat Dalmuti server is running.');console.log(`This computer: http://localhost:${PORT}`);for(const ip of ips())console.log(`Other devices: http://${ip}:${PORT}`);console.log('\nPress Ctrl+C to stop.\n')});
