const http=require('http'),fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto');
const {URL}=require('url');const E=require('./game-engine');
const PORT=Number(process.env.PORT||3000),HOST='0.0.0.0',PUBLIC=path.join(__dirname,'public'),rooms=new Map(),MAX_PLAYERS=10,MIN_PLAYERS=4;
const MIME={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};
function cleanName(v){const s=String(v||'').replace(/\s+/g,' ').trim().slice(0,14);if(!s)throw Error('닉네임을 입력해 주세요.');return s}
function cleanMessage(v){const s=String(v||'').replace(/\s+/g,' ').trim().slice(0,120);if(!s)throw Error('메시지를 입력해 주세요.');return s}
function cleanCode(v){return String(v||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase().slice(0,6)}
function newCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';for(let z=0;z<999;z++){let s='';for(let i=0;i<5;i++)s+=chars[Math.floor(Math.random()*chars.length)];if(!rooms.has(s))return s}throw Error('방 코드를 만들지 못했습니다.')}
function getRoom(v){const r=rooms.get(cleanCode(v));if(!r)throw Error('방을 찾을 수 없습니다.');return r}
function auth(p){const r=getRoom(p.roomCode),u=r.players.find(x=>x.id===p.playerId&&x.token===p.reconnectToken);if(!u)throw Error('재접속 정보가 올바르지 않습니다.');return{r,u}}
function session(r,u){return{roomCode:r.code,playerId:u.id,reconnectToken:u.token}}
function roleName(i,n){if(i===0)return'대 달무티';if(i===1)return'소 달무티';if(i===n-2)return'소 농노';if(i===n-1)return'대 농노';return'상인'}
function normalizeGameRoles(g){g.players.sort((a,b)=>a.roleIndex-b.roleIndex);g.players.forEach((p,i)=>{p.roleIndex=i;p.seat=i;p.role=roleName(i,g.players.length)})}
function normalizedRoomRules(r){r.rules=E.normalizeRules(r.rules);return r.rules}
function isActivePlayer(r,id){return!!r.game?.players.some(p=>p.id===id)}
function currentDalmutiId(r){if(!r.game)return null;const present=new Set(r.players.map(p=>p.id));return[...r.game.players].sort((a,b)=>a.roleIndex-b.roleIndex).find(p=>present.has(p.id))?.id||null}
function publicGame(r,viewer){const g=r.game;if(!g)return null;return{status:g.status,handNumber:g.handNumber,phase:g.phase,currentPlayerId:g.currentPlayerId,pile:g.pile?{...g.pile,playerName:g.players.find(p=>p.id===g.pile.playerId)?.name||''}:null,passers:g.passers,finishOrder:g.finishOrder,winnerId:g.winnerId,logs:g.logs.slice(-50),viewerWaiting:!g.players.some(p=>p.id===viewer),rules:g.rules,deckSize:80,discardedCount:g.discardedCount,jokerNeed:2,tax:g.phase==='revolution'?{eligibleForViewer:g.tax.eligible.includes(viewer),declined:g.tax.declined.includes(viewer)}:g.phase==='tax'?{stage:g.tax.stage,pending:g.currentPlayerId===viewer?g.tax.pending:null}:null,players:g.players.map(p=>({id:p.id,name:p.name,role:p.role,roleIndex:p.roleIndex,connected:p.connected,handCount:p.hand.length,finished:p.finished,finishPlace:p.finishPlace,hand:p.id===viewer?p.hand.map(c=>({id:c.id,rank:c.rank})):null}))}}
function state(r,v){normalizedRoomRules(r);return{room:{code:r.code,maxPlayers:MAX_PLAYERS,hostId:r.hostId,dalmutiId:currentDalmutiId(r),rules:r.rules,testRoom:!!r.testRoom,players:r.players.map(p=>({id:p.id,name:p.name,connected:p.connected,waiting:!!r.game&&!isActivePlayer(r,p.id),bot:!!p.bot})),started:!!r.game,chat:r.chat.slice(-60)},viewerId:v,game:publicGame(r,v)}}
function publicRooms(){return[...rooms.values()].filter(r=>r.players.length&&!r.testRoom).map(r=>({code:r.code,count:r.players.length,maxPlayers:MAX_PLAYERS,started:!!r.game,joinable:r.players.length<MAX_PLAYERS})).sort((a,b)=>Number(a.started)-Number(b.started)||b.count-a.count||a.code.localeCompare(b.code))}
function sse(res,event,data){try{res.write(`event: ${event}\ndata: ${JSON.stringify(data)}\n\n`);return true}catch{return false}}
function emit(r){if(r.game)for(const gp of r.game.players){const lp=r.players.find(x=>x.id===gp.id);gp.connected=!!lp?.connected}for(const p of r.players)if(p.stream&&!sse(p.stream,'state',state(r,p.id))){p.stream=null;p.connected=false}}
function transferHost(r){if(!r.players.find(p=>p.id===r.hostId))r.hostId=r.players.find(p=>!p.bot)?.id||r.players[0]?.id||null}
function removeRoomPlayer(r,target,eventName=null,message=''){if(target.stream){if(eventName)sse(target.stream,eventName,{message});target.stream.end();target.stream=null}r.players=r.players.filter(x=>x.id!==target.id);transferHost(r)}
function pruneDepartedPlayers(r){if(!r.game)return;const present=new Set(r.players.map(p=>p.id));r.game.players=r.game.players.filter(p=>present.has(p.id));r.game.finishOrder=r.game.finishOrder.filter(id=>present.has(id));r.game.passers=r.game.passers.filter(id=>present.has(id));normalizeGameRoles(r.game)}
function addWaitingPlayersForNextHand(r){const g=r.game,newcomers=r.players.filter(p=>!g.players.some(x=>x.id===p.id));for(const u of newcomers)g.players.push({id:u.id,name:u.name,connected:u.connected,seat:g.players.length,roleIndex:g.players.length,role:'대 농노',hand:[],finished:false,finishPlace:null});if(newcomers.length)normalizeGameRoles(g);return newcomers}
function restartWithoutPlayer(r,targetName,targetId){const g=r.game;g.players=g.players.filter(p=>p.id!==targetId);g.finishOrder=g.finishOrder.filter(id=>id!==targetId);g.passers=g.passers.filter(id=>id!==targetId);normalizeGameRoles(g);const newcomers=addWaitingPlayersForNextHand(r);if(g.players.length<MIN_PLAYERS){r.game=null;return false}E.restartHand(g,r.rules);g.logs.push(`${targetName}님을 제외하고 새 판을 시작했습니다.`);if(newcomers.length)g.logs.push(`${newcomers.map(x=>x.name).join(', ')}님이 대농노 쪽 계급으로 합류했습니다.`);return true}
function setRules(r,u,p){if(p.remainderMode===undefined)return;const editor=r.game?currentDalmutiId(r):r.hostId;if(u.id!==editor)throw Error(r.game?'남는 카드 분배는 대 달무티만 변경할 수 있습니다.':'남는 카드 분배는 방장만 변경할 수 있습니다.');r.rules=E.normalizeRules({remainderMode:p.remainderMode});r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:`다음 판 남는 카드: ${{low:'낮은 계급부터 지급',high:'높은 계급부터 지급',discard:'버리기'}[r.rules.remainderMode]}.`,at:Date.now()})}
function isBot(r,id){return!!r.players.find(p=>p.id===id)?.bot}
function botReturnCards(p,n){const cards=[...p.hand].sort((a,b)=>{const aw=a.rank===13?0:a.rank,bw=b.rank===13?0:b.rank;return bw-aw||b.rank-a.rank});return cards.slice(0,n).map(c=>c.id)}
function botPlayIds(g,p){const jokers=p.hand.filter(c=>c.rank===13),groups=new Map();for(const c of p.hand)if(c.rank!==13){if(!groups.has(c.rank))groups.set(c.rank,[]);groups.get(c.rank).push(c)}if(!g.pile){const ranks=[...groups.keys()].sort((a,b)=>b-a);if(ranks.length){const cards=groups.get(ranks[0]);return cards.map(c=>c.id)}return jokers.length?[jokers[0].id]:[]}const need=g.pile.count,candidates=[];for(const [rank,cards] of groups){if(rank>=g.pile.rank)continue;const useJ=Math.max(0,need-cards.length);if(useJ<=jokers.length&&cards.length+useJ>=need)candidates.push({rank,ids:[...cards.slice(0,need),...jokers.slice(0,useJ)].slice(0,need).map(c=>c.id)})}candidates.sort((a,b)=>b.rank-a.rank);return candidates[0]?.ids||[]}
function scheduleBot(r){if(!r.testRoom||r.botTimer)return;r.botTimer=setTimeout(()=>{r.botTimer=null;runBot(r)},420)}
function runBot(r){const g=r.game;if(!r.testRoom||!g)return;if(g.phase==='revolution'){const id=g.tax.eligible.find(id=>isBot(r,id)&&!g.tax.declined.includes(id));if(id){try{E.declineRevolution(g,id)}catch{}emit(r);scheduleBot(r);return}}
if(g.phase==='tax'&&isBot(r,g.currentPlayerId)){const p=g.players.find(x=>x.id===g.currentPlayerId);try{E.taxReturn(g,p.id,botReturnCards(p,g.tax.pending.count))}catch{}emit(r);scheduleBot(r);return}
if(g.phase==='play'&&isBot(r,g.currentPlayerId)){const p=g.players.find(x=>x.id===g.currentPlayerId),ids=botPlayIds(g,p);try{if(ids.length)E.playCards(g,p.id,ids);else E.pass(g,p.id)}catch{try{if(g.pile)E.pass(g,p.id)}catch{}}emit(r);scheduleBot(r);return}
if(g.phase==='results'){const gd=g.players.find(x=>x.roleIndex===0);if(gd&&isBot(r,gd.id)){try{E.nextHand(g,gd.id,r.rules)}catch{}emit(r);scheduleBot(r)}}}
function afterAction(r){emit(r);scheduleBot(r)}
const A={
'create-room':p=>{const u={id:crypto.randomUUID(),token:crypto.randomUUID(),name:cleanName(p.name),connected:true,stream:null},r={code:newCode(),hostId:u.id,players:[u],game:null,chat:[],rules:{remainderMode:'low'}};rooms.set(r.code,r);return{session:session(r,u),state:state(r,u.id)}},
'create-test-room':p=>{const u={id:crypto.randomUUID(),token:crypto.randomUUID(),name:cleanName(p.name||'테스터'),connected:true,stream:null},bots=[1,2,3].map(i=>({id:crypto.randomUUID(),token:crypto.randomUUID(),name:`테스트봇${i}`,connected:true,stream:null,bot:true})),r={code:newCode(),hostId:u.id,players:[u,...bots],game:null,chat:[],rules:{remainderMode:'low'},testRoom:true,botTimer:null};rooms.set(r.code,r);r.game=E.createGame(r.players.map(x=>({id:x.id,name:x.name,connected:true})),r.rules);r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:'혼자 테스트할 수 있는 4인 테스트 방입니다. 봇은 자동으로 플레이합니다.',at:Date.now()});scheduleBot(r);return{session:session(r,u),state:state(r,u.id)}},
'join-room':p=>{const r=getRoom(p.roomCode),name=cleanName(p.name),existing=r.players.find(x=>x.name.toLowerCase()===name.toLowerCase());if(r.testRoom)throw Error('테스트 방에는 추가 참가할 수 없습니다.');if(existing){if(existing.connected)throw Error('같은 닉네임이 이미 접속 중입니다.');existing.token=crypto.randomUUID();existing.connected=true;afterAction(r);return{session:session(r,existing),state:state(r,existing.id)}}if(r.players.length>=MAX_PLAYERS)throw Error('방이 가득 찼습니다. 최대 10명입니다.');const u={id:crypto.randomUUID(),token:crypto.randomUUID(),name,connected:true,stream:null};r.players.push(u);if(r.game)r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:`${name}님이 입장했습니다. 다음 판부터 대농노로 합류합니다.`,at:Date.now()});afterAction(r);return{session:session(r,u),state:state(r,u.id)}},
'reconnect-session':p=>{const{r,u}=auth(p);u.connected=true;afterAction(r);return{session:session(r,u),state:state(r,u.id)}},
'leave-room':p=>{const{r,u}=auth(p),gp=r.game?.players.find(x=>x.id===u.id),finished=!!gp&&(gp.finished||gp.hand.length===0),name=u.name;if(u.stream){u.stream.end();u.stream=null}removeRoomPlayer(r,u);let restarted=false;if(gp&&!finished&&r.game)restarted=restartWithoutPlayer(r,name,u.id);else if(gp){gp.connected=false;gp.departed=true}if(!r.players.filter(x=>!x.bot).length){if(r.botTimer)clearTimeout(r.botTimer);rooms.delete(r.code);return{}}r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:gp&&!finished?(restarted?`${name}님이 나가 현재 판을 취소하고 새 판을 시작했습니다.`:`${name}님이 나갔습니다. 인원이 4명 미만이라 로비로 돌아갑니다.`):`${name}님이 방을 나갔습니다.`,at:Date.now()});afterAction(r);return{}},
'update-rules':p=>{const{r,u}=auth(p);setRules(r,u,p);afterAction(r);return{}},
'kick-player':p=>{const{r,u}=auth(p);if(u.id!==r.hostId)throw Error('방장만 강퇴할 수 있습니다.');const target=r.players.find(x=>x.id===p.targetPlayerId);if(!target)throw Error('대상을 찾을 수 없습니다.');if(target.id===u.id)throw Error('자기 자신은 강퇴할 수 없습니다.');if(target.bot)throw Error('테스트 봇은 강퇴할 수 없습니다.');const active=isActivePlayer(r,target.id),name=target.name;removeRoomPlayer(r,target,'kicked','방장에 의해 강퇴되었습니다.');const restarted=active&&r.game?restartWithoutPlayer(r,name,target.id):false;r.chat.push({id:crypto.randomUUID(),playerId:'system',name:'시스템',text:active?(restarted?`${name}님을 제외하고 새 판을 시작했습니다.`:`${name}님이 강퇴되었습니다. 인원이 4명 미만이라 로비로 돌아갑니다.`):`${name}님이 방장에 의해 강퇴되었습니다.`,at:Date.now()});afterAction(r);return{}},
'start-game':p=>{const{r,u}=auth(p);if(u.id!==r.hostId)throw Error('방장만 시작할 수 있습니다.');if(r.players.length<MIN_PLAYERS)throw Error('최소 4명이 필요합니다.');if(r.players.length>MAX_PLAYERS)throw Error('최대 10명까지 가능합니다.');r.game=E.createGame(r.players.map(x=>({id:x.id,name:x.name,connected:true})),r.rules);afterAction(r);return{}},
'declare-revolution':p=>{const{r,u}=auth(p);E.declareRevolution(r.game,u.id,!!p.greater);afterAction(r);return{}},
'decline-revolution':p=>{const{r,u}=auth(p);E.declineRevolution(r.game,u.id);afterAction(r);return{}},
'tax-return':p=>{const{r,u}=auth(p);E.taxReturn(r.game,u.id,p.cardIds);afterAction(r);return{}},
'play-cards':p=>{const{r,u}=auth(p);E.playCards(r.game,u.id,p.cardIds);afterAction(r);return{}},
'pass':p=>{const{r,u}=auth(p);E.pass(r.game,u.id);afterAction(r);return{}},
'next-hand':p=>{const{r,u}=auth(p),g=r.game;if(g.phase!=='results')throw Error('현재 판이 끝나지 않았습니다.');pruneDepartedPlayers(r);const newcomers=addWaitingPlayersForNextHand(r);if(g.players.length<MIN_PLAYERS){r.game=null;afterAction(r);return{}}const gd=g.players.find(x=>x.roleIndex===0);if(u.id!==gd?.id)throw Error('새 대 달무티만 다음 판을 시작할 수 있습니다.');if(newcomers.length)g.logs.push(`${newcomers.map(x=>x.name).join(', ')}님이 새 대농노 계급으로 합류합니다.`);E.nextHand(g,u.id,r.rules);afterAction(r);return{}},
'send-chat':p=>{const{r,u}=auth(p);r.chat.push({id:crypto.randomUUID(),playerId:u.id,name:u.name,text:cleanMessage(p.message),at:Date.now()});if(r.chat.length>80)r.chat.splice(0,r.chat.length-80);afterAction(r);return{}}
};
function json(res,status,obj){const b=JSON.stringify(obj);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(b)});res.end(b)}
function body(req){return new Promise((ok,no)=>{let s='';req.on('data',d=>{s+=d;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}});req.on('error',no)})}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/api/rooms')return json(res,200,{ok:true,rooms:publicRooms()});if(req.method==='POST'&&u.pathname==='/api/action'){const p=await body(req),fn=A[p.type];if(!fn)throw Error('알 수 없는 요청입니다.');return json(res,200,{ok:true,...fn(p)})}if(req.method==='GET'&&u.pathname==='/api/events'){const p=Object.fromEntries(u.searchParams),{r,u:pl}=auth(p);if(pl.stream)pl.stream.end();pl.connected=true;res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache','Connection':'keep-alive'});pl.stream=res;sse(res,'state',state(r,pl.id));req.on('close',()=>{if(pl.stream===res){pl.stream=null;pl.connected=false;emit(r)}});return}let f=u.pathname==='/'?'index.html':decodeURIComponent(u.pathname.slice(1));f=path.normalize(f).replace(/^(\.\.[/\\])+/, '');const full=path.join(PUBLIC,f);if(!full.startsWith(PUBLIC)||!fs.existsSync(full)||fs.statSync(full).isDirectory()){res.writeHead(404);return res.end('Not found')}res.writeHead(200,{'Content-Type':MIME[path.extname(full)]||'application/octet-stream','Cache-Control':'no-store'});fs.createReadStream(full).pipe(res)}catch(e){json(res,400,{ok:false,error:e.message||'오류가 발생했습니다.'})}});
function ips(){const a=[];for(const xs of Object.values(os.networkInterfaces()))for(const x of xs||[])if(x.family==='IPv4'&&!x.internal)a.push(x.address);return a}
server.listen(PORT,HOST,()=>{console.log('\nGreat Dalmuti server is running.');console.log(`This computer: http://localhost:${PORT}`);for(const ip of ips())console.log(`Other devices: http://${ip}:${PORT}`);console.log('\nPress Ctrl+C to stop.\n')});
